### PR TITLE
Integrate Dan's changes

### LINKED ISSUE #1: Designated initializers do not correspond appropriately to the new structure layouts
Previously, the compiler would segfault when compiling the Linux kernel.

Now, it just leaks memory until the OOM killer reaps it.

```
$ cd linux
$ make CC=/path/to/this/fork/llvm-project/build/bin/clang
```

Lots of good help from the original repo: https://github.com/clang-randstruct/llvm-project/issues/42

If I understand this correctly, the designated initializers are assigning values pre-randomization and as a result, everything melts down post-randomization.

So I suppose two ways forward would be to:

1. Move the layout randomization sooner in the semantic analysis process (libSema)
2. (or) Figure out where the designated initializers are created in their `InitListExpr`s and perform some kind of field mapping so when the initializer thinks "oh this value goes into offset 4" a mapping takes place to maps offset 4 to the offset where the field has moved to post randomization.

### LINKED ISSUE #2: Add support for randomization seed
- [x] Add support for using the seed with the RNG engine
- [x] Add a compiler flag for passing this seed

### PR DESCRIPTION
**Pull request by connorkuehl**
From here: https://github.com/da-x/llvm-project/commits/clang-r365631c-randstruct

This is a ~~first~~ now second draft at merging in Dan's changes with the newer Randstruct code. I left notes on what I changed around to merge it in when I was cherry-picking commits.

Closes #1 
Closes #2 

v1 -> v2:

- [x] Only exclude last field from randomization if and only if it is a variable-length array, or an array of length 0 or 1.
- [x] Command-line seed should have higher priority than filename seed
- [x] Fixup bad cast for randomized struct by confirming it's randomized (previously changing the condition to `!= 0` but now instead just checking a flag.
- [ ] Optimization: don't check for bad casts if the struct has not been randomized

### CODE REVIEW

File: clang/lib/AST/Randstruct.cpp [hunk 1]
```diff
@@ -212,7 +212,9 @@ void randomizeStructureLayout(const ASTContext &Context, const RecordDecl *RD) {
       Field->setOriginalFieldIndex(index);
       ++index;
 
-      if (Field->getType()->isIncompleteArrayType()) {
+      auto Type = Field->getType();
+      auto *ZSA = dyn_cast<ConstantArrayType>(Type);
+      if ((ZSA && ZSA->getSize() == 0) || Type->isIncompleteArrayType()) {
```
Comment (da-x) [inline clang/lib/AST/Randstruct.cpp]: Not sure about this implementation - we can have multiple `[0]` arrays in the same struct and get unexpected results, in this case the `VLA` local variable would get overridden by multiple assignments. IMHO should try here to be as conservative as possible and fine-grain the check have the last field excluded from randomization if and only if it's a `[]`, `[0]` array (and also `[1]` if being paranoid like the GCC plugin).

File: clang/lib/Sema/AnalysisBasedWarnings.cpp [hunk 2]
```diff
@@ -2253,6 +2313,8 @@ AnalysisBasedWarnings::IssueWarnings(sema::AnalysisBasedWarnings::Policy P,
       ++NumFunctionsWithBadCFGs;
     }
   }
+
+  clang::randstruct::casts::checkForBadCasts(S, AC);
```
Comment (da-x) [inline clang/lib/Sema/AnalysisBasedWarnings.cpp:2315]: As an optimization we can skip the check altogether if no randomized struct was declared or used.

File: clang/lib/Sema/AnalysisBasedWarnings.cpp [hunk 3]
```diff
@@ -1967,6 +1968,65 @@ class ConsumedWarningsHandler : public ConsumedWarningsHandlerBase {
...
+	  auto E_SP = ((QualType)E_T)->getPointeeType();
+	  auto ICE_PT = ((QualType)ICE_T)->getPointeeType();
+
+	  auto E_R = E_SP->getAsRecordDecl();
+	  auto ICE_R = ICE_PT->getAsRecordDecl();
+
+	  if (E_R != nullptr && ICE_R != nullptr && E_R != ICE_R) {
+	    for (auto d : ICE_R->decls()) {
+	      auto f = dyn_cast<FieldDecl>(d);
+	      if (f != nullptr && f->getOriginalFieldIndex() == 1) {
```
Comment (da-x) [inline clang/lib/Sema/AnalysisBasedWarnings.cpp]: Reviewing my own code, I think I should have had `!= 0` here to exit immediately. The `== 1` is remnant of trying to find the original first field to see whether its type matches the type we are casting to, and limit the error to that case. I did not follow through with the original intent when later I realized that any case of a randomized struct pointer to a different struct should be flagged.

File: clang/lib/Frontend/CompilerInvocation.cpp [hunk 4]
```diff
@@ -1822,6 +1822,11 @@ static InputKind ParseFrontendArgs(FrontendOptions &Opts, ArgList &Args,
     Opts.ProgramAction = frontend::PluginAction;
     Opts.ActionName = A->getValue();
   }
+
+  if (const Arg* A = Args.getLastArg(OPT_randstruct_seed)) {
+      randstruct::SEED = A->getValue(0);
+  }
+
   if (const Arg* A = Args.getLastArg(OPT_randstruct_seed_filename)) {
```
Comment (da-x) [inline clang/lib/Frontend/CompilerInvocation.cpp:1826]: Perhaps command-line provided seed should have higher priority than file-provided seed?

**Review by da-x — COMMENTED** [review]
Here are my review commits.

File: clang/lib/Frontend/CompilerInvocation.cpp (hunk 4 above)
Comment (connorkuehl) [reply clang/lib/Frontend/CompilerInvocation.cpp:1826]: Ah yes that seems sensible, addressed here: https://github.com/connorkuehl/llvm-project/pull/21/commits/f6e9ee42040656f7538ab9cf99579dd1b54c4c19#diff-63bab2358c12cb79fff39bd2de9d3003R1835-R1839

File: clang/lib/AST/Randstruct.cpp (hunk 1 above)
Comment (connorkuehl) [reply clang/lib/AST/Randstruct.cpp]: Of course! I see what you mean. Addressed here: https://github.com/connorkuehl/llvm-project/pull/21/commits/5539309a6c1402ddfd06f9738a39637b30fce3fa#diff-5c7d62977f531ddbbd167bd919830134R228-R238

File: clang/lib/Sema/AnalysisBasedWarnings.cpp (hunk 3 above)
Comment (connorkuehl) [reply clang/lib/Sema/AnalysisBasedWarnings.cpp]: I fixed this up here: https://github.com/connorkuehl/llvm-project/pull/21/commits/8177f0c3ff9bdaf0c999f685b3c8ee436bfeabe0#diff-0b2bca3c80bdf15abfb7ce3d2f8b1557R2001

But I added support for marking a structure that has been processed by Randstruct and I think made the equivalent change here: https://github.com/connorkuehl/llvm-project/pull/21/commits/9d81226ce5a6acab1e7b14c13f60c73a057c271b#diff-0b2bca3c80bdf15abfb7ce3d2f8b1557R1999-R2003

File: clang/lib/Sema/AnalysisBasedWarnings.cpp (hunk 2 above)
Comment (connorkuehl) [reply clang/lib/Sema/AnalysisBasedWarnings.cpp:2315]: This makes sense, I just need to figure out how to get access to relevant RecordDecl's to check them.

File: clang/lib/Sema/AnalysisBasedWarnings.cpp (hunk 3 above)
Comment (connorkuehl) [reply clang/lib/Sema/AnalysisBasedWarnings.cpp]: I fixed this up here: https://github.com/connorkuehl/llvm-project/pull/21/commits/8177f0c3ff9bdaf0c999f685b3c8ee436bfeabe0#diff-0b2bca3c80bdf15abfb7ce3d2f8b1557R2001

but after adding support for marking structures that have been randomized, I replaced it with what I think is equivalent logic: https://github.com/connorkuehl/llvm-project/pull/21/commits/9d81226ce5a6acab1e7b14c13f60c73a057c271b#diff-0b2bca3c80bdf15abfb7ce3d2f8b1557R1999-R2003
